name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make application.yml
        if: |
          contains(github.ref, 'main')
        run: |
          cd ./src/main/resources 
          touch ./application.yml 
          echo "${{ secrets.YML }}" > ./application.yml
        shell: bash

      - name: Make application-db.yml
        if: |
          contains(github.ref, 'main')
        run: |
          cd ./src/main/resources 
          touch ./application-db.yml 
          echo "${{ secrets.YML_DB }}" > ./application-db.yml
        shell: bash

      - name: Make application-jwt.yml
        if: |
          contains(github.ref, 'main')
        run: |
          cd ./src/main/resources 
          touch ./application-jwt.yml 
          echo "${{ secrets.YML_JWT }}" > ./application-jwt.yml
        shell: bash

      - name: Make application-fcm.yml
        if: |
          contains(github.ref, 'main')
        run: |
          cd ./src/main/resources 
          touch ./application-fcm.yml 
          echo "${{ secrets.YML_JWT }}" > ./application-fcm.yml
        shell: bash

      - name: Make application-oauth.yml
        if: |
          contains(github.ref, 'main')
        run: |
          cd ./src/main/resources 
          touch ./application-oauth.yml 
          echo "${{ secrets.YML_OAUTH }}" > ./application-oauth.yml
        shell: bash

      - name: Make application-aws.yml
        if: |
          contains(github.ref, 'main')
        run: |
          cd ./src/main/resources 
          touch ./application-aws.yml 
          echo "${{ secrets.YML_AWS }}" > ./application-aws.yml
        shell: bash

      - name: Make apple key.yml
        if: |
          contains(github.ref, 'main')
        run: |
          mkdir -p ./src/main/resources/keys
          echo "${{ secrets.APPLE_KEY }}" > ./src/main/resources/keys/AuthKey_D69RVU73XV.p8
        shell: bash

      - name: Make firebase directory
        if: contains(github.ref, 'main')
        run: |
          mkdir -p ./src/main/resources/firebase
        shell: bash

      - name: Create FCM key JSON
        if: contains(github.ref, 'main')
        uses: jsdaniell/create-json@1.1.2
        with:
          destination: ./src/main/resources/firebase/bunout-2ed63-firebase-adminsdk-5dr7p-2f2195cbc8.json
          data: ${{ secrets.FIREBASE_SECRET_KEY }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image build & Push
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/bunout .
          docker push ${{ secrets.DOCKER_USERNAME }}/bunout

      - name: Get GitHub IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Add Ip to SG
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker ps
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm $(sudo docker ps --filter 'status=exited' -q)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/bunout
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/bunout
            sudo docker image prune -a -f

      - name: Revoke IP from SG
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
